package io.ipinfo.api.context;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import io.ipinfo.api.model.Continent;
import io.ipinfo.api.model.CountryCurrency;
import io.ipinfo.api.model.CountryFlag;

public class Context {
    private final Map<String, String> countryMap = new HashMap<>();
    private final Map<String, CountryFlag> countriesFlags = new HashMap<>();
    private final Map<String, CountryCurrency> countriesCurrencies = new HashMap<>();
    private final Map<String, Continent> continents = new HashMap<>();
    private final List<String> euCountries = new ArrayList<>();
    private final static String CountryFlagURL = "https://cdn.ipinfo.io/static/images/countries-flags/";

    public Context() 
        {
            populateCountryMap();
            populateEuCountriesList();
            populateCountryFlagsMap();
            populateCountriesCurrenciesMap();
            populateContinentsMap();
        }

    public String getCountryName(String countryCode) {
        return countryMap.get(countryCode);
    }

    public CountryFlag getCountryFlag(String countryCode) {
        return countriesFlags.get(countryCode);
    }

    public String getCountryFlagURL(String countryCode) {
        return Context.CountryFlagURL + countryCode + ".svg";
    }

    public CountryCurrency getCountryCurrency(String countryCode) {
        return countriesCurrencies.get(countryCode);
    }

    public Continent getContinent(String countryCode) {
        return continents.get(countryCode);
    }

    public boolean isEU(String countryCode) {
        return euCountries.contains(countryCode);
    }

    private void populateCountryMap() {
        countryMap.put("BD", "Bangladesh");
        countryMap.put("BE", "Belgium");
        countryMap.put("BF", "Burkina Faso");
        countryMap.put("BG", "Bulgaria");
        countryMap.put("BA", "Bosnia and Herzegovina");
        countryMap.put("BB", "Barbados");
        countryMap.put("WF", "Wallis and Futuna");
        countryMap.put("BL", "Saint Barthelemy");
        countryMap.put("BM", "Bermuda");
        countryMap.put("BN", "Brunei");
        countryMap.put("BO", "Bolivia");
        countryMap.put("BH", "Bahrain");
        countryMap.put("BI", "Burundi");
        countryMap.put("BJ", "Benin");
        countryMap.put("BT", "Bhutan");
        countryMap.put("JM", "Jamaica");
        countryMap.put("BV", "Bouvet Island");
        countryMap.put("BW", "Botswana");
        countryMap.put("WS", "Samoa");
        countryMap.put("BQ", "Bonaire, Saint Eustatius and Saba");
        countryMap.put("BR", "Brazil");
        countryMap.put("BS", "Bahamas");
        countryMap.put("JE", "Jersey");
        countryMap.put("BY", "Belarus");
        countryMap.put("BZ", "Belize");
        countryMap.put("RU", "Russia");
        countryMap.put("RW", "Rwanda");
        countryMap.put("RS", "Serbia");
        countryMap.put("TL", "East Timor");
        countryMap.put("RE", "Reunion");
        countryMap.put("TM", "Turkmenistan");
        countryMap.put("TJ", "Tajikistan");
        countryMap.put("RO", "Romania");
        countryMap.put("TK", "Tokelau");
        countryMap.put("GW", "Guinea-Bissau");
        countryMap.put("GU", "Guam");
        countryMap.put("GT", "Guatemala");
        countryMap.put("GS", "South Georgia and the South Sandwich Islands");
        countryMap.put("GR", "Greece");
        countryMap.put("GQ", "Equatorial Guinea");
        countryMap.put("GP", "Guadeloupe");
        countryMap.put("JP", "Japan");
        countryMap.put("GY", "Guyana");
        countryMap.put("GG", "Guernsey");
        countryMap.put("GF", "French Guiana");
        countryMap.put("GE", "Georgia");
        countryMap.put("GD", "Grenada");
        countryMap.put("GB", "United Kingdom");
        countryMap.put("GA", "Gabon");
        countryMap.put("SV", "El Salvador");
        countryMap.put("GN", "Guinea");
        countryMap.put("GM", "Gambia");
        countryMap.put("GL", "Greenland");
        countryMap.put("GI", "Gibraltar");
        countryMap.put("GH", "Ghana");
        countryMap.put("OM", "Oman");
        countryMap.put("TN", "Tunisia");
        countryMap.put("JO", "Jordan");
        countryMap.put("HR", "Croatia");
        countryMap.put("HT", "Haiti");
        countryMap.put("HU", "Hungary");
        countryMap.put("HK", "Hong Kong");
        countryMap.put("HN", "Honduras");
        countryMap.put("HM", "Heard Island and McDonald Islands");
        countryMap.put("VE", "Venezuela");
        countryMap.put("PR", "Puerto Rico");
        countryMap.put("PS", "Palestinian Territory");
        countryMap.put("PW", "Palau");
        countryMap.put("PT", "Portugal");
        countryMap.put("SJ", "Svalbard and Jan Mayen");
        countryMap.put("PY", "Paraguay");
        countryMap.put("IQ", "Iraq");
        countryMap.put("PA", "Panama");
        countryMap.put("PF", "French Polynesia");
        countryMap.put("PG", "Papua New Guinea");
        countryMap.put("PE", "Peru");
        countryMap.put("PK", "Pakistan");
        countryMap.put("PH", "Philippines");
        countryMap.put("PN", "Pitcairn");
        countryMap.put("PL", "Poland");
        countryMap.put("PM", "Saint Pierre and Miquelon");
        countryMap.put("ZM", "Zambia");
        countryMap.put("EH", "Western Sahara");
        countryMap.put("EE", "Estonia");
        countryMap.put("EG", "Egypt");
        countryMap.put("ZA", "South Africa");
        countryMap.put("EC", "Ecuador");
        countryMap.put("IT", "Italy");
        countryMap.put("VN", "Vietnam");
        countryMap.put("SB", "Solomon Islands");
        countryMap.put("ET", "Ethiopia");
        countryMap.put("SO", "Somalia");
        countryMap.put("ZW", "Zimbabwe");
        countryMap.put("SA", "Saudi Arabia");
        countryMap.put("ES", "Spain");
        countryMap.put("ER", "Eritrea");
        countryMap.put("ME", "Montenegro");
        countryMap.put("MD", "Moldova");
        countryMap.put("MG", "Madagascar");
        countryMap.put("MF", "Saint Martin");
        countryMap.put("MA", "Morocco");
        countryMap.put("MC", "Monaco");
        countryMap.put("UZ", "Uzbekistan");
        countryMap.put("MM", "Myanmar");
        countryMap.put("ML", "Mali");
        countryMap.put("MO", "Macao");
        countryMap.put("MN", "Mongolia");
        countryMap.put("MH", "Marshall Islands");
        countryMap.put("MK", "Macedonia");
        countryMap.put("MU", "Mauritius");
        countryMap.put("MT", "Malta");
        countryMap.put("MW", "Malawi");
        countryMap.put("MV", "Maldives");
        countryMap.put("MQ", "Martinique");
        countryMap.put("MP", "Northern Mariana Islands");
        countryMap.put("MS", "Montserrat");
        countryMap.put("MR", "Mauritania");
        countryMap.put("IM", "Isle of Man");
        countryMap.put("UG", "Uganda");
        countryMap.put("TZ", "Tanzania");
        countryMap.put("MY", "Malaysia");
        countryMap.put("MX", "Mexico");
        countryMap.put("IL", "Israel");
        countryMap.put("FR", "France");
        countryMap.put("IO", "British Indian Ocean Territory");
        countryMap.put("SH", "Saint Helena");
        countryMap.put("FI", "Finland");
        countryMap.put("FJ", "Fiji");
        countryMap.put("FK", "Falkland Islands");
        countryMap.put("FM", "Micronesia");
        countryMap.put("FO", "Faroe Islands");
        countryMap.put("NI", "Nicaragua");
        countryMap.put("NL", "Netherlands");
        countryMap.put("NO", "Norway");
        countryMap.put("NA", "Namibia");
        countryMap.put("VU", "Vanuatu");
        countryMap.put("NC", "New Caledonia");
        countryMap.put("NE", "Niger");
        countryMap.put("NF", "Norfolk Island");
        countryMap.put("NG", "Nigeria");
        countryMap.put("NZ", "New Zealand");
        countryMap.put("NP", "Nepal");
        countryMap.put("NR", "Nauru");
        countryMap.put("NU", "Niue");
        countryMap.put("CK", "Cook Islands");
        countryMap.put("XK", "Kosovo");
        countryMap.put("CI", "Ivory Coast");
        countryMap.put("CH", "Switzerland");
        countryMap.put("CO", "Colombia");
        countryMap.put("CN", "China");
        countryMap.put("CM", "Cameroon");
        countryMap.put("CL", "Chile");
        countryMap.put("CC", "Cocos Islands");
        countryMap.put("CA", "Canada");
        countryMap.put("CG", "Republic of the Congo");
        countryMap.put("CF", "Central African Republic");
        countryMap.put("CD", "Democratic Republic of the Congo");
        countryMap.put("CZ", "Czech Republic");
        countryMap.put("CY", "Cyprus");
        countryMap.put("CX", "Christmas Island");
        countryMap.put("CR", "Costa Rica");
        countryMap.put("CW", "Curacao");
        countryMap.put("CV", "Cape Verde");
        countryMap.put("CU", "Cuba");
        countryMap.put("SZ", "Swaziland");
        countryMap.put("SY", "Syria");
        countryMap.put("SX", "Sint Maarten");
        countryMap.put("KG", "Kyrgyzstan");
        countryMap.put("KE", "Kenya");
        countryMap.put("SS", "South Sudan");
        countryMap.put("SR", "Suriname");
        countryMap.put("KI", "Kiribati");
        countryMap.put("KH", "Cambodia");
        countryMap.put("KN", "Saint Kitts and Nevis");
        countryMap.put("KM", "Comoros");
        countryMap.put("ST", "Sao Tome and Principe");
        countryMap.put("SK", "Slovakia");
        countryMap.put("KR", "South Korea");
        countryMap.put("SI", "Slovenia");
        countryMap.put("KP", "North Korea");
        countryMap.put("KW", "Kuwait");
        countryMap.put("SN", "Senegal");
        countryMap.put("SM", "San Marino");
        countryMap.put("SL", "Sierra Leone");
        countryMap.put("SC", "Seychelles");
        countryMap.put("KZ", "Kazakhstan");
        countryMap.put("KY", "Cayman Islands");
        countryMap.put("SG", "Singapore");
        countryMap.put("SE", "Sweden");
        countryMap.put("SD", "Sudan");
        countryMap.put("DO", "Dominican Republic");
        countryMap.put("DM", "Dominica");
        countryMap.put("DJ", "Djibouti");
        countryMap.put("DK", "Denmark");
        countryMap.put("VG", "British Virgin Islands");
        countryMap.put("DE", "Germany");
        countryMap.put("YE", "Yemen");
        countryMap.put("DZ", "Algeria");
        countryMap.put("US", "United States");
        countryMap.put("UY", "Uruguay");
        countryMap.put("YT", "Mayotte");
        countryMap.put("UM", "United States Minor Outlying Islands");
        countryMap.put("LB", "Lebanon");
        countryMap.put("LC", "Saint Lucia");
        countryMap.put("LA", "Laos");
        countryMap.put("TV", "Tuvalu");
        countryMap.put("TW", "Taiwan");
        countryMap.put("TT", "Trinidad and Tobago");
        countryMap.put("TR", "Turkey");
        countryMap.put("LK", "Sri Lanka");
        countryMap.put("LI", "Liechtenstein");
        countryMap.put("LV", "Latvia");
        countryMap.put("TO", "Tonga");
        countryMap.put("LT", "Lithuania");
        countryMap.put("LU", "Luxembourg");
        countryMap.put("LR", "Liberia");
        countryMap.put("LS", "Lesotho");
        countryMap.put("TH", "Thailand");
        countryMap.put("TF", "French Southern Territories");
        countryMap.put("TG", "Togo");
        countryMap.put("TD", "Chad");
        countryMap.put("TC", "Turks and Caicos Islands");
        countryMap.put("LY", "Libya");
        countryMap.put("VA", "Vatican");
        countryMap.put("VC", "Saint Vincent and the Grenadines");
        countryMap.put("AE", "United Arab Emirates");
        countryMap.put("AD", "Andorra");
        countryMap.put("AG", "Antigua and Barbuda");
        countryMap.put("AF", "Afghanistan");
        countryMap.put("AI", "Anguilla");
        countryMap.put("VI", "U.S. Virgin Islands");
        countryMap.put("IS", "Iceland");
        countryMap.put("IR", "Iran");
        countryMap.put("AM", "Armenia");
        countryMap.put("AL", "Albania");
        countryMap.put("AO", "Angola");
        countryMap.put("AQ", "Antarctica");
        countryMap.put("AS", "American Samoa");
        countryMap.put("AR", "Argentina");
        countryMap.put("AU", "Australia");
        countryMap.put("AT", "Austria");
        countryMap.put("AW", "Aruba");
        countryMap.put("IN", "India");
        countryMap.put("AX", "Aland Islands");
        countryMap.put("AZ", "Azerbaijan");
        countryMap.put("IE", "Ireland");
        countryMap.put("ID", "Indonesia");
        countryMap.put("UA", "Ukraine");
        countryMap.put("QA", "Qatar");
        countryMap.put("MZ", "Mozambique");
    }

    private void populateEuCountriesList() {
        // Add the provided EU country codes to the euCountries list
        Collections.addAll(euCountries, "IE", "AT", "LT", "LU", "LV", "DE", "DK", "SE", "SI", "SK", "CZ", "CY", "NL", "FI", "FR", "MT", "ES", "IT", "EE", "PL", "PT", "HU", "HR", "GR", "RO", "BG", "BE");
    }

    private void populateCountryFlagsMap() {
        countriesFlags.put("AD", new CountryFlag("🇦🇩", "U+1F1E6 U+1F1E9"));
        countriesFlags.put("AE", new CountryFlag("🇦🇪", "U+1F1E6 U+1F1EA"));
        countriesFlags.put("AF", new CountryFlag("🇦🇫", "U+1F1E6 U+1F1EB"));
        countriesFlags.put("AG", new CountryFlag("🇦🇬", "U+1F1E6 U+1F1EC"));
        countriesFlags.put("AI", new CountryFlag("🇦🇮", "U+1F1E6 U+1F1EE"));
        countriesFlags.put("AL", new CountryFlag("🇦🇱", "U+1F1E6 U+1F1F1"));
        countriesFlags.put("AM", new CountryFlag("🇦🇲", "U+1F1E6 U+1F1F2"));
        countriesFlags.put("AO", new CountryFlag("🇦🇴", "U+1F1E6 U+1F1F4"));
        countriesFlags.put("AQ", new CountryFlag("🇦🇶", "U+1F1E6 U+1F1F6"));
        countriesFlags.put("AR", new CountryFlag("🇦🇷", "U+1F1E6 U+1F1F7"));
        countriesFlags.put("AS", new CountryFlag("🇦🇸", "U+1F1E6 U+1F1F8"));
        countriesFlags.put("AT", new CountryFlag("🇦🇹", "U+1F1E6 U+1F1F9"));
        countriesFlags.put("AU", new CountryFlag("🇦🇺", "U+1F1E6 U+1F1FA"));
        countriesFlags.put("AW", new CountryFlag("🇦🇼", "U+1F1E6 U+1F1FC"));
        countriesFlags.put("AX", new CountryFlag("🇦🇽", "U+1F1E6 U+1F1FD"));
        countriesFlags.put("AZ", new CountryFlag("🇦🇿", "U+1F1E6 U+1F1FF"));
        countriesFlags.put("BA", new CountryFlag("🇧🇦", "U+1F1E7 U+1F1E6"));
        countriesFlags.put("BB", new CountryFlag("🇧🇧", "U+1F1E7 U+1F1E7"));
        countriesFlags.put("BD", new CountryFlag("🇧🇩", "U+1F1E7 U+1F1E9"));
        countriesFlags.put("BE", new CountryFlag("🇧🇪", "U+1F1E7 U+1F1EA"));
        countriesFlags.put("BF", new CountryFlag("🇧🇫", "U+1F1E7 U+1F1EB"));
        countriesFlags.put("BG", new CountryFlag("🇧🇬", "U+1F1E7 U+1F1EC"));
        countriesFlags.put("BH", new CountryFlag("🇧🇭", "U+1F1E7 U+1F1ED"));
        countriesFlags.put("BI", new CountryFlag("🇧🇮", "U+1F1E7 U+1F1EE"));
        countriesFlags.put("BJ", new CountryFlag("🇧🇯", "U+1F1E7 U+1F1EF"));
        countriesFlags.put("BL", new CountryFlag("🇧🇱", "U+1F1E7 U+1F1F1"));
        countriesFlags.put("BM", new CountryFlag("🇧🇲", "U+1F1E7 U+1F1F2"));
        countriesFlags.put("BN", new CountryFlag("🇧🇳", "U+1F1E7 U+1F1F3"));
        countriesFlags.put("BO", new CountryFlag("🇧🇴", "U+1F1E7 U+1F1F4"));
        countriesFlags.put("BQ", new CountryFlag("🇧🇶", "U+1F1E7 U+1F1F6"));
        countriesFlags.put("BR", new CountryFlag("🇧🇷", "U+1F1E7 U+1F1F7"));
        countriesFlags.put("BS", new CountryFlag("🇧🇸", "U+1F1E7 U+1F1F8"));
        countriesFlags.put("BT", new CountryFlag("🇧🇹", "U+1F1E7 U+1F1F9"));
        countriesFlags.put("BV", new CountryFlag("🇧🇻", "U+1F1E7 U+1F1FB"));
        countriesFlags.put("BW", new CountryFlag("🇧🇼", "U+1F1E7 U+1F1FC"));
        countriesFlags.put("BY", new CountryFlag("🇧🇾", "U+1F1E7 U+1F1FE"));
        countriesFlags.put("BZ", new CountryFlag("🇧🇿", "U+1F1E7 U+1F1FF"));
        countriesFlags.put("CA", new CountryFlag("🇨🇦", "U+1F1E8 U+1F1E6"));
        countriesFlags.put("CC", new CountryFlag("🇨🇨", "U+1F1E8 U+1F1E8"));
        countriesFlags.put("CD", new CountryFlag("🇨🇩", "U+1F1E8 U+1F1E9"));
        countriesFlags.put("CF", new CountryFlag("🇨🇫", "U+1F1E8 U+1F1EB"));
        countriesFlags.put("CG", new CountryFlag("🇨🇬", "U+1F1E8 U+1F1EC"));
        countriesFlags.put("CH", new CountryFlag("🇨🇭", "U+1F1E8 U+1F1ED"));
        countriesFlags.put("CI", new CountryFlag("🇨🇮", "U+1F1E8 U+1F1EE"));
        countriesFlags.put("CK", new CountryFlag("🇨🇰", "U+1F1E8 U+1F1F0"));
        countriesFlags.put("CL", new CountryFlag("🇨🇱", "U+1F1E8 U+1F1F1"));
        countriesFlags.put("CM", new CountryFlag("🇨🇲", "U+1F1E8 U+1F1F2"));
        countriesFlags.put("CN", new CountryFlag("🇨🇳", "U+1F1E8 U+1F1F3"));
        countriesFlags.put("CO", new CountryFlag("🇨🇴", "U+1F1E8 U+1F1F4"));
        countriesFlags.put("CR", new CountryFlag("🇨🇷", "U+1F1E8 U+1F1F7"));
        countriesFlags.put("CU", new CountryFlag("🇨🇺", "U+1F1E8 U+1F1FA"));
        countriesFlags.put("CV", new CountryFlag("🇨🇻", "U+1F1E8 U+1F1FB"));
        countriesFlags.put("CW", new CountryFlag("🇨🇼", "U+1F1E8 U+1F1FC"));
        countriesFlags.put("CX", new CountryFlag("🇨🇽", "U+1F1E8 U+1F1FD"));
        countriesFlags.put("CY", new CountryFlag("🇨🇾", "U+1F1E8 U+1F1FE"));
        countriesFlags.put("CZ", new CountryFlag("🇨🇿", "U+1F1E8 U+1F1FF"));
        countriesFlags.put("DE", new CountryFlag("🇩🇪", "U+1F1E9 U+1F1EA"));
        countriesFlags.put("DJ", new CountryFlag("🇩🇯", "U+1F1E9 U+1F1EF"));
        countriesFlags.put("DK", new CountryFlag("🇩🇰", "U+1F1E9 U+1F1F0"));
        countriesFlags.put("DM", new CountryFlag("🇩🇲", "U+1F1E9 U+1F1F2"));
        countriesFlags.put("DO", new CountryFlag("🇩🇴", "U+1F1E9 U+1F1F4"));
        countriesFlags.put("DZ", new CountryFlag("🇩🇿", "U+1F1E9 U+1F1FF"));
        countriesFlags.put("EC", new CountryFlag("🇪🇨", "U+1F1EA U+1F1E8"));
        countriesFlags.put("EE", new CountryFlag("🇪🇪", "U+1F1EA U+1F1EA"));
        countriesFlags.put("EG", new CountryFlag("🇪🇬", "U+1F1EA U+1F1EC"));
        countriesFlags.put("EH", new CountryFlag("🇪🇭", "U+1F1EA U+1F1ED"));
        countriesFlags.put("ER", new CountryFlag("🇪🇷", "U+1F1EA U+1F1F7"));
        countriesFlags.put("ES", new CountryFlag("🇪🇸", "U+1F1EA U+1F1F8"));
        countriesFlags.put("ET", new CountryFlag("🇪🇹", "U+1F1EA U+1F1F9"));
        countriesFlags.put("FI", new CountryFlag("🇫🇮", "U+1F1EB U+1F1EE"));
        countriesFlags.put("FJ", new CountryFlag("🇫🇯", "U+1F1EB U+1F1EF"));
        countriesFlags.put("FK", new CountryFlag("🇫🇰", "U+1F1EB U+1F1F0"));
        countriesFlags.put("FM", new CountryFlag("🇫🇲", "U+1F1EB U+1F1F2"));
        countriesFlags.put("FO", new CountryFlag("🇫🇴", "U+1F1EB U+1F1F4"));
        countriesFlags.put("FR", new CountryFlag("🇫🇷", "U+1F1EB U+1F1F7"));
        countriesFlags.put("GA", new CountryFlag("🇬🇦", "U+1F1EC U+1F1E6"));
        countriesFlags.put("GB", new CountryFlag("🇬🇧", "U+1F1EC U+1F1E7"));
        countriesFlags.put("GD", new CountryFlag("🇬🇩", "U+1F1EC U+1F1E9"));
        countriesFlags.put("GE", new CountryFlag("🇬🇪", "U+1F1EC U+1F1EA"));
        countriesFlags.put("GF", new CountryFlag("🇬🇫", "U+1F1EC U+1F1EB"));
        countriesFlags.put("GG", new CountryFlag("🇬🇬", "U+1F1EC U+1F1EC"));
        countriesFlags.put("GH", new CountryFlag("🇬🇭", "U+1F1EC U+1F1ED"));
        countriesFlags.put("GI", new CountryFlag("🇬🇮", "U+1F1EC U+1F1EE"));
        countriesFlags.put("GL", new CountryFlag("🇬🇱", "U+1F1EC U+1F1F1"));
        countriesFlags.put("GM", new CountryFlag("🇬🇲", "U+1F1EC U+1F1F2"));
        countriesFlags.put("GN", new CountryFlag("🇬🇳", "U+1F1EC U+1F1F3"));
        countriesFlags.put("GP", new CountryFlag("🇬🇵", "U+1F1EC U+1F1F5"));
        countriesFlags.put("GQ", new CountryFlag("🇬🇶", "U+1F1EC U+1F1F6"));
        countriesFlags.put("GR", new CountryFlag("🇬🇷", "U+1F1EC U+1F1F7"));
        countriesFlags.put("GS", new CountryFlag("🇬🇸", "U+1F1EC U+1F1F8"));
        countriesFlags.put("GT", new CountryFlag("🇬🇹", "U+1F1EC U+1F1F9"));
        countriesFlags.put("GU", new CountryFlag("🇬🇺", "U+1F1EC U+1F1FA"));
        countriesFlags.put("GW", new CountryFlag("🇬🇼", "U+1F1EC U+1F1FC"));
        countriesFlags.put("GY", new CountryFlag("🇬🇾", "U+1F1EC U+1F1FE"));
        countriesFlags.put("HK", new CountryFlag("🇭🇰", "U+1F1ED U+1F1F0"));
        countriesFlags.put("HM", new CountryFlag("🇭🇲", "U+1F1ED U+1F1F2"));
        countriesFlags.put("HN", new CountryFlag("🇭🇳", "U+1F1ED U+1F1F3"));
        countriesFlags.put("HR", new CountryFlag("🇭🇷", "U+1F1ED U+1F1F7"));
        countriesFlags.put("HT", new CountryFlag("🇭🇹", "U+1F1ED U+1F1F9"));
        countriesFlags.put("HU", new CountryFlag("🇭🇺", "U+1F1ED U+1F1FA"));
        countriesFlags.put("ID", new CountryFlag("🇮🇩", "U+1F1EE U+1F1E9"));
        countriesFlags.put("IE", new CountryFlag("🇮🇪", "U+1F1EE U+1F1EA"));
        countriesFlags.put("IL", new CountryFlag("🇮🇱", "U+1F1EE U+1F1F1"));
        countriesFlags.put("IM", new CountryFlag("🇮🇲", "U+1F1EE U+1F1F2"));
        countriesFlags.put("IN", new CountryFlag("🇮🇳", "U+1F1EE U+1F1F3"));
        countriesFlags.put("IO", new CountryFlag("🇮🇴", "U+1F1EE U+1F1F4"));
        countriesFlags.put("IQ", new CountryFlag("🇮🇶", "U+1F1EE U+1F1F6"));
        countriesFlags.put("IR", new CountryFlag("🇮🇷", "U+1F1EE U+1F1F7"));
        countriesFlags.put("IS", new CountryFlag("🇮🇸", "U+1F1EE U+1F1F8"));
        countriesFlags.put("IT", new CountryFlag("🇮🇹", "U+1F1EE U+1F1F9"));
        countriesFlags.put("JE", new CountryFlag("🇯🇪", "U+1F1EF U+1F1EA"));
        countriesFlags.put("JM", new CountryFlag("🇯🇲", "U+1F1EF U+1F1F2"));
        countriesFlags.put("JO", new CountryFlag("🇯🇴", "U+1F1EF U+1F1F4"));
        countriesFlags.put("JP", new CountryFlag("🇯🇵", "U+1F1EF U+1F1F5"));
        countriesFlags.put("KE", new CountryFlag("🇰🇪", "U+1F1F0 U+1F1EA"));
        countriesFlags.put("KG", new CountryFlag("🇰🇬", "U+1F1F0 U+1F1EC"));
        countriesFlags.put("KH", new CountryFlag("🇰🇭", "U+1F1F0 U+1F1ED"));
        countriesFlags.put("KI", new CountryFlag("🇰🇮", "U+1F1F0 U+1F1EE"));
        countriesFlags.put("KM", new CountryFlag("🇰🇲", "U+1F1F0 U+1F1F2"));
        countriesFlags.put("KN", new CountryFlag("🇰🇳", "U+1F1F0 U+1F1F3"));
        countriesFlags.put("KP", new CountryFlag("🇰🇵", "U+1F1F0 U+1F1F5"));
        countriesFlags.put("KR", new CountryFlag("🇰🇷", "U+1F1F0 U+1F1F7"));
        countriesFlags.put("KW", new CountryFlag("🇰🇼", "U+1F1F0 U+1F1FC"));
        countriesFlags.put("KY", new CountryFlag("🇰🇾", "U+1F1F0 U+1F1FE"));
        countriesFlags.put("KZ", new CountryFlag("🇰🇿", "U+1F1F0 U+1F1FF"));
        countriesFlags.put("LA", new CountryFlag("🇱🇦", "U+1F1F1 U+1F1E6"));
        countriesFlags.put("LB", new CountryFlag("🇱🇧", "U+1F1F1 U+1F1E7"));
        countriesFlags.put("LC", new CountryFlag("🇱🇨", "U+1F1F1 U+1F1E8"));
        countriesFlags.put("LI", new CountryFlag("🇱🇮", "U+1F1F1 U+1F1EE"));
        countriesFlags.put("LK", new CountryFlag("🇱🇰", "U+1F1F1 U+1F1F0"));
        countriesFlags.put("LR", new CountryFlag("🇱🇷", "U+1F1F1 U+1F1F7"));
        countriesFlags.put("LS", new CountryFlag("🇱🇸", "U+1F1F1 U+1F1F8"));
        countriesFlags.put("LT", new CountryFlag("🇱🇹", "U+1F1F1 U+1F1F9"));
        countriesFlags.put("LU", new CountryFlag("🇱🇺", "U+1F1F1 U+1F1FA"));
        countriesFlags.put("LV", new CountryFlag("🇱🇻", "U+1F1F1 U+1F1FB"));
        countriesFlags.put("LY", new CountryFlag("🇱🇾", "U+1F1F1 U+1F1FE"));
        countriesFlags.put("MA", new CountryFlag("🇲🇦", "U+1F1F2 U+1F1E6"));
        countriesFlags.put("MC", new CountryFlag("🇲🇨", "U+1F1F2 U+1F1E8"));
        countriesFlags.put("MD", new CountryFlag("🇲🇩", "U+1F1F2 U+1F1E9"));
        countriesFlags.put("ME", new CountryFlag("🇲🇪", "U+1F1F2 U+1F1EA"));
        countriesFlags.put("MF", new CountryFlag("🇲🇫", "U+1F1F2 U+1F1EB"));
        countriesFlags.put("MG", new CountryFlag("🇲🇬", "U+1F1F2 U+1F1EC"));
        countriesFlags.put("MH", new CountryFlag("🇲🇭", "U+1F1F2 U+1F1ED"));
        countriesFlags.put("MK", new CountryFlag("🇲🇰", "U+1F1F2 U+1F1F0"));
        countriesFlags.put("ML", new CountryFlag("🇲🇱", "U+1F1F2 U+1F1F1"));
        countriesFlags.put("MM", new CountryFlag("🇲🇲", "U+1F1F2 U+1F1F2"));
        countriesFlags.put("MN", new CountryFlag("🇲🇳", "U+1F1F2 U+1F1F3"));
        countriesFlags.put("MO", new CountryFlag("🇲🇴", "U+1F1F2 U+1F1F4"));
        countriesFlags.put("MP", new CountryFlag("🇲🇵", "U+1F1F2 U+1F1F5"));
        countriesFlags.put("MQ", new CountryFlag("🇲🇶", "U+1F1F2 U+1F1F6"));
        countriesFlags.put("MR", new CountryFlag("🇲🇷", "U+1F1F2 U+1F1F7"));
        countriesFlags.put("MS", new CountryFlag("🇲🇸", "U+1F1F2 U+1F1F8"));
        countriesFlags.put("MT", new CountryFlag("🇲🇹", "U+1F1F2 U+1F1F9"));
        countriesFlags.put("MU", new CountryFlag("🇲🇺", "U+1F1F2 U+1F1FA"));
        countriesFlags.put("MV", new CountryFlag("🇲🇻", "U+1F1F2 U+1F1FB"));
        countriesFlags.put("MW", new CountryFlag("🇲🇼", "U+1F1F2 U+1F1FC"));
        countriesFlags.put("MX", new CountryFlag("🇲🇽", "U+1F1F2 U+1F1FD"));
        countriesFlags.put("MY", new CountryFlag("🇲🇾", "U+1F1F2 U+1F1FE"));
        countriesFlags.put("MZ", new CountryFlag("🇲🇿", "U+1F1F2 U+1F1FF"));
        countriesFlags.put("NA", new CountryFlag("🇳🇦", "U+1F1F3 U+1F1E6"));
        countriesFlags.put("NC", new CountryFlag("🇳🇨", "U+1F1F3 U+1F1E8"));
        countriesFlags.put("NE", new CountryFlag("🇳🇪", "U+1F1F3 U+1F1EA"));
        countriesFlags.put("NF", new CountryFlag("🇳🇫", "U+1F1F3 U+1F1EB"));
        countriesFlags.put("NG", new CountryFlag("🇳🇬", "U+1F1F3 U+1F1EC"));
        countriesFlags.put("NI", new CountryFlag("🇳🇮", "U+1F1F3 U+1F1EE"));
        countriesFlags.put("NL", new CountryFlag("🇳🇱", "U+1F1F3 U+1F1F1"));
        countriesFlags.put("NO", new CountryFlag("🇳🇴", "U+1F1F3 U+1F1F4"));
        countriesFlags.put("NP", new CountryFlag("🇳🇵", "U+1F1F3 U+1F1F5"));
        countriesFlags.put("NR", new CountryFlag("🇳🇷", "U+1F1F3 U+1F1F7"));
        countriesFlags.put("NU", new CountryFlag("🇳🇺", "U+1F1F3 U+1F1FA"));
        countriesFlags.put("NZ", new CountryFlag("🇳🇿", "U+1F1F3 U+1F1FF"));
        countriesFlags.put("OM", new CountryFlag("🇴🇲", "U+1F1F4 U+1F1F2"));
        countriesFlags.put("PA", new CountryFlag("🇵🇦", "U+1F1F5 U+1F1E6"));
        countriesFlags.put("PE", new CountryFlag("🇵🇪", "U+1F1F5 U+1F1EA"));
        countriesFlags.put("PF", new CountryFlag("🇵🇫", "U+1F1F5 U+1F1EB"));
        countriesFlags.put("PG", new CountryFlag("🇵🇬", "U+1F1F5 U+1F1EC"));
        countriesFlags.put("PH", new CountryFlag("🇵🇭", "U+1F1F5 U+1F1ED"));
        countriesFlags.put("PK", new CountryFlag("🇵🇰", "U+1F1F5 U+1F1F0"));
        countriesFlags.put("PL", new CountryFlag("🇵🇱", "U+1F1F5 U+1F1F1"));
        countriesFlags.put("PM", new CountryFlag("🇵🇲", "U+1F1F5 U+1F1F2"));
        countriesFlags.put("PN", new CountryFlag("🇵🇳", "U+1F1F5 U+1F1F3"));
        countriesFlags.put("PR", new CountryFlag("🇵🇷", "U+1F1F5 U+1F1F7"));
        countriesFlags.put("PS", new CountryFlag("🇵🇸", "U+1F1F5 U+1F1F8"));
        countriesFlags.put("PT", new CountryFlag("🇵🇹", "U+1F1F5 U+1F1F9"));
        countriesFlags.put("PW", new CountryFlag("🇵🇼", "U+1F1F5 U+1F1FC"));
        countriesFlags.put("PY", new CountryFlag("🇵🇾", "U+1F1F5 U+1F1FE"));
        countriesFlags.put("QA", new CountryFlag("🇶🇦", "U+1F1F6 U+1F1E6"));
        countriesFlags.put("RE", new CountryFlag("🇷🇪", "U+1F1F7 U+1F1EA"));
        countriesFlags.put("RO", new CountryFlag("🇷🇴", "U+1F1F7 U+1F1F4"));
        countriesFlags.put("RS", new CountryFlag("🇷🇸", "U+1F1F7 U+1F1F8"));
        countriesFlags.put("RU", new CountryFlag("🇷🇺", "U+1F1F7 U+1F1FA"));
        countriesFlags.put("RW", new CountryFlag("🇷🇼", "U+1F1F7 U+1F1FC"));
        countriesFlags.put("SA", new CountryFlag("🇸🇦", "U+1F1F8 U+1F1E6"));
        countriesFlags.put("SB", new CountryFlag("🇸🇧", "U+1F1F8 U+1F1E7"));
        countriesFlags.put("SC", new CountryFlag("🇸🇨", "U+1F1F8 U+1F1E8"));
        countriesFlags.put("SD", new CountryFlag("🇸🇩", "U+1F1F8 U+1F1E9"));
        countriesFlags.put("SE", new CountryFlag("🇸🇪", "U+1F1F8 U+1F1EA"));
        countriesFlags.put("SG", new CountryFlag("🇸🇬", "U+1F1F8 U+1F1EC"));
        countriesFlags.put("SH", new CountryFlag("🇸🇭", "U+1F1F8 U+1F1ED"));
        countriesFlags.put("SI", new CountryFlag("🇸🇮", "U+1F1F8 U+1F1EE"));
        countriesFlags.put("SJ", new CountryFlag("🇸🇯", "U+1F1F8 U+1F1EF"));
        countriesFlags.put("SK", new CountryFlag("🇸🇰", "U+1F1F8 U+1F1F0"));
        countriesFlags.put("SL", new CountryFlag("🇸🇱", "U+1F1F8 U+1F1F1"));
        countriesFlags.put("SM", new CountryFlag("🇸🇲", "U+1F1F8 U+1F1F2"));
        countriesFlags.put("SN", new CountryFlag("🇸🇳", "U+1F1F8 U+1F1F3"));
        countriesFlags.put("SO", new CountryFlag("🇸🇴", "U+1F1F8 U+1F1F4"));
        countriesFlags.put("SR", new CountryFlag("🇸🇷", "U+1F1F8 U+1F1F7"));
        countriesFlags.put("SS", new CountryFlag("🇸🇸", "U+1F1F8 U+1F1F8"));
        countriesFlags.put("ST", new CountryFlag("🇸🇹", "U+1F1F8 U+1F1F9"));
        countriesFlags.put("SV", new CountryFlag("🇸🇻", "U+1F1F8 U+1F1FB"));
        countriesFlags.put("SX", new CountryFlag("🇸🇽", "U+1F1F8 U+1F1FD"));
        countriesFlags.put("SY", new CountryFlag("🇸🇾", "U+1F1F8 U+1F1FE"));
        countriesFlags.put("SZ", new CountryFlag("🇸🇿", "U+1F1F8 U+1F1FF"));
        countriesFlags.put("TC", new CountryFlag("🇹🇨", "U+1F1F9 U+1F1E8"));
        countriesFlags.put("TD", new CountryFlag("🇹🇩", "U+1F1F9 U+1F1E9"));
        countriesFlags.put("TF", new CountryFlag("🇹🇫", "U+1F1F9 U+1F1EB"));
        countriesFlags.put("TG", new CountryFlag("🇹🇬", "U+1F1F9 U+1F1EC"));
        countriesFlags.put("TH", new CountryFlag("🇹🇭", "U+1F1F9 U+1F1ED"));
        countriesFlags.put("TJ", new CountryFlag("🇹🇯", "U+1F1F9 U+1F1EF"));
        countriesFlags.put("TK", new CountryFlag("🇹🇰", "U+1F1F9 U+1F1F0"));
        countriesFlags.put("TL", new CountryFlag("🇹🇱", "U+1F1F9 U+1F1F1"));
        countriesFlags.put("TM", new CountryFlag("🇹🇲", "U+1F1F9 U+1F1F2"));
        countriesFlags.put("TN", new CountryFlag("🇹🇳", "U+1F1F9 U+1F1F3"));
        countriesFlags.put("TO", new CountryFlag("🇹🇴", "U+1F1F9 U+1F1F4"));
        countriesFlags.put("TR", new CountryFlag("🇹🇷", "U+1F1F9 U+1F1F7"));
        countriesFlags.put("TT", new CountryFlag("🇹🇹", "U+1F1F9 U+1F1F9"));
        countriesFlags.put("TV", new CountryFlag("🇹🇻", "U+1F1F9 U+1F1FB"));
        countriesFlags.put("TW", new CountryFlag("🇹🇼", "U+1F1F9 U+1F1FC"));
        countriesFlags.put("TZ", new CountryFlag("🇹🇿", "U+1F1F9 U+1F1FF"));
        countriesFlags.put("UA", new CountryFlag("🇺🇦", "U+1F1FA U+1F1E6"));
        countriesFlags.put("UG", new CountryFlag("🇺🇬", "U+1F1FA U+1F1EC"));
        countriesFlags.put("UM", new CountryFlag("🇺🇲", "U+1F1FA U+1F1F2"));
        countriesFlags.put("US", new CountryFlag("🇺🇸", "U+1F1FA U+1F1F8"));
        countriesFlags.put("UY", new CountryFlag("🇺🇾", "U+1F1FA U+1F1FE"));
        countriesFlags.put("UZ", new CountryFlag("🇺🇿", "U+1F1FA U+1F1FF"));
        countriesFlags.put("VA", new CountryFlag("🇻🇦", "U+1F1FB U+1F1E6"));
        countriesFlags.put("VC", new CountryFlag("🇻🇨", "U+1F1FB U+1F1E8"));
        countriesFlags.put("VE", new CountryFlag("🇻🇪", "U+1F1FB U+1F1EA"));
        countriesFlags.put("VG", new CountryFlag("🇻🇬", "U+1F1FB U+1F1EC"));
        countriesFlags.put("VI", new CountryFlag("🇻🇮", "U+1F1FB U+1F1EE"));
        countriesFlags.put("VN", new CountryFlag("🇻🇳", "U+1F1FB U+1F1F3"));
        countriesFlags.put("VU", new CountryFlag("🇻🇺", "U+1F1FB U+1F1FA"));
        countriesFlags.put("WF", new CountryFlag("🇼🇫", "U+1F1FC U+1F1EB"));
        countriesFlags.put("WS", new CountryFlag("🇼🇸", "U+1F1FC U+1F1F8"));
        countriesFlags.put("XK", new CountryFlag("🇽🇰", "U+1F1FD U+1F1F0"));
        countriesFlags.put("YE", new CountryFlag("🇾🇪", "U+1F1FE U+1F1EA"));
        countriesFlags.put("YT", new CountryFlag("🇾🇹", "U+1F1FE U+1F1F9"));
        countriesFlags.put("ZA", new CountryFlag("🇿🇦", "U+1F1FF U+1F1E6"));
        countriesFlags.put("ZM", new CountryFlag("🇿🇲", "U+1F1FF U+1F1F2"));
        countriesFlags.put("ZW", new CountryFlag("🇿🇼", "U+1F1FF U+1F1FC"));
    }

    private void populateCountriesCurrenciesMap() {
        countriesCurrencies.put("AD", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("AE", new CountryCurrency("AED", "د.إ"));
        countriesCurrencies.put("AF", new CountryCurrency("AFN", "؋"));
        countriesCurrencies.put("AG", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("AI", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("AL", new CountryCurrency("ALL", "L"));
        countriesCurrencies.put("AM", new CountryCurrency("AMD", "֏"));
        countriesCurrencies.put("AO", new CountryCurrency("AOA", "Kz"));
        countriesCurrencies.put("AQ", new CountryCurrency("", "$"));
        countriesCurrencies.put("AR", new CountryCurrency("ARS", "$"));
        countriesCurrencies.put("AS", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("AT", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("AU", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("AW", new CountryCurrency("AWG", "ƒ"));
        countriesCurrencies.put("AX", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("AZ", new CountryCurrency("AZN", "₼"));
        countriesCurrencies.put("BA", new CountryCurrency("BAM", "KM"));
        countriesCurrencies.put("BB", new CountryCurrency("BBD", "$"));
        countriesCurrencies.put("BD", new CountryCurrency("BDT", "৳"));
        countriesCurrencies.put("BE", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("BF", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("BG", new CountryCurrency("BGN", "лв"));
        countriesCurrencies.put("BH", new CountryCurrency("BHD", ".د.ب"));
        countriesCurrencies.put("BI", new CountryCurrency("BIF", "FBu"));
        countriesCurrencies.put("BJ", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("BL", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("BM", new CountryCurrency("BMD", "$"));
        countriesCurrencies.put("BN", new CountryCurrency("BND", "$"));
        countriesCurrencies.put("BO", new CountryCurrency("BOB", "$b"));
        countriesCurrencies.put("BQ", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("BR", new CountryCurrency("BRL", "R$"));
        countriesCurrencies.put("BS", new CountryCurrency("BSD", "$"));
        countriesCurrencies.put("BT", new CountryCurrency("BTN", "Nu."));
        countriesCurrencies.put("BV", new CountryCurrency("NOK", "kr"));
        countriesCurrencies.put("BW", new CountryCurrency("BWP", "P"));
        countriesCurrencies.put("BY", new CountryCurrency("BYR", "Br"));
        countriesCurrencies.put("BZ", new CountryCurrency("BZD", "BZ$"));
        countriesCurrencies.put("CA", new CountryCurrency("CAD", "$"));
        countriesCurrencies.put("CC", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("CD", new CountryCurrency("CDF", "FC"));
        countriesCurrencies.put("CF", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("CG", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("CH", new CountryCurrency("CHF", "CHF"));
        countriesCurrencies.put("CI", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("CK", new CountryCurrency("NZD", "$"));
        countriesCurrencies.put("CL", new CountryCurrency("CLP", "$"));
        countriesCurrencies.put("CM", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("CN", new CountryCurrency("CNY", "¥"));
        countriesCurrencies.put("CO", new CountryCurrency("COP", "$"));
        countriesCurrencies.put("CR", new CountryCurrency("CRC", "₡"));
        countriesCurrencies.put("CU", new CountryCurrency("CUP", "₱"));
        countriesCurrencies.put("CV", new CountryCurrency("CVE", "$"));
        countriesCurrencies.put("CW", new CountryCurrency("ANG", "ƒ"));
        countriesCurrencies.put("CX", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("CY", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("CZ", new CountryCurrency("CZK", "Kč"));
        countriesCurrencies.put("DE", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("DJ", new CountryCurrency("DJF", "Fdj"));
        countriesCurrencies.put("DK", new CountryCurrency("DKK", "kr"));
        countriesCurrencies.put("DM", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("DO", new CountryCurrency("DOP", "RD$"));
        countriesCurrencies.put("DZ", new CountryCurrency("DZD", "دج"));
        countriesCurrencies.put("EC", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("EE", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("EG", new CountryCurrency("EGP", "£"));
        countriesCurrencies.put("EH", new CountryCurrency("MAD", "MAD"));
        countriesCurrencies.put("ER", new CountryCurrency("ERN", "Nfk"));
        countriesCurrencies.put("ES", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("ET", new CountryCurrency("ETB", "Br"));
        countriesCurrencies.put("FI", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("FJ", new CountryCurrency("FJD", "$"));
        countriesCurrencies.put("FK", new CountryCurrency("FKP", "£"));
        countriesCurrencies.put("FM", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("FO", new CountryCurrency("DKK", "kr"));
        countriesCurrencies.put("FR", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("GA", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("GB", new CountryCurrency("GBP", "£"));
        countriesCurrencies.put("GD", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("GE", new CountryCurrency("GEL", "ლ"));
        countriesCurrencies.put("GF", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("GG", new CountryCurrency("GBP", "£"));
        countriesCurrencies.put("GH", new CountryCurrency("GHS", "GH₵"));
        countriesCurrencies.put("GI", new CountryCurrency("GIP", "£"));
        countriesCurrencies.put("GL", new CountryCurrency("DKK", "kr"));
        countriesCurrencies.put("GM", new CountryCurrency("GMD", "D"));
        countriesCurrencies.put("GN", new CountryCurrency("GNF", "FG"));
        countriesCurrencies.put("GP", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("GQ", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("GR", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("GS", new CountryCurrency("GBP", "£"));
        countriesCurrencies.put("GT", new CountryCurrency("GTQ", "Q"));
        countriesCurrencies.put("GU", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("GW", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("GY", new CountryCurrency("GYD", "$"));
        countriesCurrencies.put("HK", new CountryCurrency("HKD", "$"));
        countriesCurrencies.put("HM", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("HN", new CountryCurrency("HNL", "L"));
        countriesCurrencies.put("HR", new CountryCurrency("HRK", "kn"));
        countriesCurrencies.put("HT", new CountryCurrency("HTG", "G"));
        countriesCurrencies.put("HU", new CountryCurrency("HUF", "Ft"));
        countriesCurrencies.put("ID", new CountryCurrency("IDR", "Rp"));
        countriesCurrencies.put("IE", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("IL", new CountryCurrency("ILS", "₪"));
        countriesCurrencies.put("IM", new CountryCurrency("GBP", "£"));
        countriesCurrencies.put("IN", new CountryCurrency("INR", "₹"));
        countriesCurrencies.put("IO", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("IQ", new CountryCurrency("IQD", "ع.د"));
        countriesCurrencies.put("IR", new CountryCurrency("IRR", "﷼"));
        countriesCurrencies.put("IS", new CountryCurrency("ISK", "kr"));
        countriesCurrencies.put("IT", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("JE", new CountryCurrency("GBP", "£"));
        countriesCurrencies.put("JM", new CountryCurrency("JMD", "J$"));
        countriesCurrencies.put("JO", new CountryCurrency("JOD", "JD"));
        countriesCurrencies.put("JP", new CountryCurrency("JPY", "¥"));
        countriesCurrencies.put("KE", new CountryCurrency("KES", "KSh"));
        countriesCurrencies.put("KG", new CountryCurrency("KGS", "лв"));
        countriesCurrencies.put("KH", new CountryCurrency("KHR", "៛"));
        countriesCurrencies.put("KI", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("KM", new CountryCurrency("KMF", "CF"));
        countriesCurrencies.put("KN", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("KP", new CountryCurrency("KPW", "₩"));
        countriesCurrencies.put("KR", new CountryCurrency("KRW", "₩"));
        countriesCurrencies.put("KW", new CountryCurrency("KWD", "KD"));
        countriesCurrencies.put("KY", new CountryCurrency("KYD", "$"));
        countriesCurrencies.put("KZ", new CountryCurrency("KZT", "₸"));
        countriesCurrencies.put("LA", new CountryCurrency("LAK", "₭"));
        countriesCurrencies.put("LB", new CountryCurrency("LBP", "£"));
        countriesCurrencies.put("LC", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("LI", new CountryCurrency("CHF", "CHF"));
        countriesCurrencies.put("LK", new CountryCurrency("LKR", "₨"));
        countriesCurrencies.put("LR", new CountryCurrency("LRD", "$"));
        countriesCurrencies.put("LS", new CountryCurrency("LSL", "M"));
        countriesCurrencies.put("LT", new CountryCurrency("LTL", "Lt"));
        countriesCurrencies.put("LU", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("LV", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("LY", new CountryCurrency("LYD", "LD"));
        countriesCurrencies.put("MA", new CountryCurrency("MAD", "MAD"));
        countriesCurrencies.put("MC", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("MD", new CountryCurrency("MDL", "lei"));
        countriesCurrencies.put("ME", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("MF", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("MG", new CountryCurrency("MGA", "Ar"));
        countriesCurrencies.put("MH", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("MK", new CountryCurrency("MKD", "ден"));
        countriesCurrencies.put("ML", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("MM", new CountryCurrency("MMK", "K"));
        countriesCurrencies.put("MN", new CountryCurrency("MNT", "₮"));
        countriesCurrencies.put("MO", new CountryCurrency("MOP", "MOP$"));
        countriesCurrencies.put("MP", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("MQ", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("MR", new CountryCurrency("MRO", "UM"));
        countriesCurrencies.put("MS", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("MT", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("MU", new CountryCurrency("MUR", "₨"));
        countriesCurrencies.put("MV", new CountryCurrency("MVR", "Rf"));
        countriesCurrencies.put("MW", new CountryCurrency("MWK", "MK"));
        countriesCurrencies.put("MX", new CountryCurrency("MXN", "$"));
        countriesCurrencies.put("MY", new CountryCurrency("MYR", "RM"));
        countriesCurrencies.put("MZ", new CountryCurrency("MZN", "MT"));
        countriesCurrencies.put("NA", new CountryCurrency("NAD", "N$"));
        countriesCurrencies.put("NC", new CountryCurrency("XPF", "₣"));
        countriesCurrencies.put("NE", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("NF", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("NG", new CountryCurrency("NGN", "₦"));
        countriesCurrencies.put("NI", new CountryCurrency("NIO", "C$"));
        countriesCurrencies.put("NL", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("NO", new CountryCurrency("NOK", "kr"));
        countriesCurrencies.put("NP", new CountryCurrency("NPR", "₨"));
        countriesCurrencies.put("NR", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("NU", new CountryCurrency("NZD", "$"));
        countriesCurrencies.put("NZ", new CountryCurrency("NZD", "$"));
        countriesCurrencies.put("OM", new CountryCurrency("OMR", "﷼"));
        countriesCurrencies.put("PA", new CountryCurrency("PAB", "B/."));
        countriesCurrencies.put("PE", new CountryCurrency("PEN", "S/"));
        countriesCurrencies.put("PF", new CountryCurrency("XPF", "₣"));
        countriesCurrencies.put("PG", new CountryCurrency("PGK", "K"));
        countriesCurrencies.put("PH", new CountryCurrency("PHP", "₱"));
        countriesCurrencies.put("PK", new CountryCurrency("PKR", "₨"));
        countriesCurrencies.put("PL", new CountryCurrency("PLN", "zł"));
        countriesCurrencies.put("PM", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("PN", new CountryCurrency("NZD", "$"));
        countriesCurrencies.put("PR", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("PS", new CountryCurrency("ILS", "₪"));
        countriesCurrencies.put("PT", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("PW", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("PY", new CountryCurrency("PYG", "₲"));
        countriesCurrencies.put("QA", new CountryCurrency("QAR", "﷼"));
        countriesCurrencies.put("RE", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("RO", new CountryCurrency("RON", "lei"));
        countriesCurrencies.put("RS", new CountryCurrency("RSD", "Дин."));
        countriesCurrencies.put("RU", new CountryCurrency("RUB", "₽"));
        countriesCurrencies.put("RW", new CountryCurrency("RWF", "FRw"));
        countriesCurrencies.put("SA", new CountryCurrency("SAR", "﷼"));
        countriesCurrencies.put("SB", new CountryCurrency("SBD", "$"));
        countriesCurrencies.put("SC", new CountryCurrency("SCR", "₨"));
        countriesCurrencies.put("SD", new CountryCurrency("SDG", "ج.س."));
        countriesCurrencies.put("SE", new CountryCurrency("SEK", "kr"));
        countriesCurrencies.put("SG", new CountryCurrency("SGD", "$"));
        countriesCurrencies.put("SH", new CountryCurrency("SHP", "£"));
        countriesCurrencies.put("SI", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("SJ", new CountryCurrency("NOK", "kr"));
        countriesCurrencies.put("SK", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("SL", new CountryCurrency("SLL", "Le"));
        countriesCurrencies.put("SM", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("SN", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("SO", new CountryCurrency("SOS", "S"));
        countriesCurrencies.put("SR", new CountryCurrency("SRD", "$"));
        countriesCurrencies.put("SS", new CountryCurrency("SSP", "£"));
        countriesCurrencies.put("ST", new CountryCurrency("STD", "Db"));
        countriesCurrencies.put("SV", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("SX", new CountryCurrency("ANG", "ƒ"));
        countriesCurrencies.put("SY", new CountryCurrency("SYP", "£"));
        countriesCurrencies.put("SZ", new CountryCurrency("SZL", "L"));
        countriesCurrencies.put("TC", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("TD", new CountryCurrency("XAF", "FCFA"));
        countriesCurrencies.put("TF", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("TG", new CountryCurrency("XOF", "CFA"));
        countriesCurrencies.put("TH", new CountryCurrency("THB", "฿"));
        countriesCurrencies.put("TJ", new CountryCurrency("TJS", "SM"));
        countriesCurrencies.put("TK", new CountryCurrency("NZD", "$"));
        countriesCurrencies.put("TL", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("TM", new CountryCurrency("TMT", "T"));
        countriesCurrencies.put("TN", new CountryCurrency("TND", "د.ت"));
        countriesCurrencies.put("TO", new CountryCurrency("TOP", "T$"));
        countriesCurrencies.put("TR", new CountryCurrency("TRY", "₺"));
        countriesCurrencies.put("TT", new CountryCurrency("TTD", "TT$"));
        countriesCurrencies.put("TV", new CountryCurrency("AUD", "$"));
        countriesCurrencies.put("TW", new CountryCurrency("TWD", "NT$"));
        countriesCurrencies.put("TZ", new CountryCurrency("TZS", "TSh"));
        countriesCurrencies.put("UA", new CountryCurrency("UAH", "₴"));
        countriesCurrencies.put("UG", new CountryCurrency("UGX", "USh"));
        countriesCurrencies.put("UM", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("US", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("UY", new CountryCurrency("UYU", "$U"));
        countriesCurrencies.put("UZ", new CountryCurrency("UZS", "лв"));
        countriesCurrencies.put("VA", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("VC", new CountryCurrency("XCD", "$"));
        countriesCurrencies.put("VE", new CountryCurrency("VEF", "Bs"));
        countriesCurrencies.put("VG", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("VI", new CountryCurrency("USD", "$"));
        countriesCurrencies.put("VN", new CountryCurrency("VND", "₫"));
        countriesCurrencies.put("VU", new CountryCurrency("VUV", "VT"));
        countriesCurrencies.put("WF", new CountryCurrency("XPF", "₣"));
        countriesCurrencies.put("WS", new CountryCurrency("WST", "WS$"));
        countriesCurrencies.put("XK", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("YE", new CountryCurrency("YER", "﷼"));
        countriesCurrencies.put("YT", new CountryCurrency("EUR", "€"));
        countriesCurrencies.put("ZA", new CountryCurrency("ZAR", "R"));
        countriesCurrencies.put("ZM", new CountryCurrency("ZMW", "ZK"));
        countriesCurrencies.put("ZW", new CountryCurrency("ZWL", "Z$"));
    }

    private void populateContinentsMap() {
        continents.put("BD", new Continent("AS", "Asia"));
        continents.put("BE", new Continent("EU", "Europe"));
        continents.put("BF", new Continent("AF", "Africa"));
        continents.put("BG", new Continent("EU", "Europe"));
        continents.put("BA", new Continent("EU", "Europe"));
        continents.put("BB", new Continent("NA", "North America"));
        continents.put("WF", new Continent("OC", "Oceania"));
        continents.put("BL", new Continent("NA", "North America"));
        continents.put("BM", new Continent("NA", "North America"));
        continents.put("BN", new Continent("AS", "Asia"));
        continents.put("BO", new Continent("SA", "South America"));
        continents.put("BH", new Continent("AS", "Asia"));
        continents.put("BI", new Continent("AF", "Africa"));
        continents.put("BJ", new Continent("AF", "Africa"));
        continents.put("BT", new Continent("AS", "Asia"));
        continents.put("JM", new Continent("NA", "North America"));
        continents.put("BV", new Continent("AN", "Antarctica"));
        continents.put("BW", new Continent("AF", "Africa"));
        continents.put("WS", new Continent("OC", "Oceania"));
        continents.put("BQ", new Continent("NA", "North America"));
        continents.put("BR", new Continent("SA", "South America"));
        continents.put("BS", new Continent("NA", "North America"));
        continents.put("JE", new Continent("EU", "Europe"));
        continents.put("BY", new Continent("EU", "Europe"));
        continents.put("BZ", new Continent("NA", "North America"));
        continents.put("RU", new Continent("EU", "Europe"));
        continents.put("RW", new Continent("AF", "Africa"));
        continents.put("RS", new Continent("EU", "Europe"));
        continents.put("TL", new Continent("OC", "Oceania"));
        continents.put("RE", new Continent("AF", "Africa"));
        continents.put("TM", new Continent("AS", "Asia"));
        continents.put("TJ", new Continent("AS", "Asia"));
        continents.put("RO", new Continent("EU", "Europe"));
        continents.put("TK", new Continent("OC", "Oceania"));
        continents.put("GW", new Continent("AF", "Africa"));
        continents.put("GU", new Continent("OC", "Oceania"));
        continents.put("GT", new Continent("NA", "North America"));
        continents.put("GS", new Continent("AN", "Antarctica"));
        continents.put("GR", new Continent("EU", "Europe"));
        continents.put("GQ", new Continent("AF", "Africa"));
        continents.put("GP", new Continent("NA", "North America"));
        continents.put("JP", new Continent("AS", "Asia"));
        continents.put("GY", new Continent("SA", "South America"));
        continents.put("GG", new Continent("EU", "Europe"));
        continents.put("GF", new Continent("SA", "South America"));
        continents.put("GE", new Continent("AS", "Asia"));
        continents.put("GD", new Continent("NA", "North America"));
        continents.put("GB", new Continent("EU", "Europe"));
        continents.put("GA", new Continent("AF", "Africa"));
        continents.put("SV", new Continent("NA", "North America"));
        continents.put("GN", new Continent("AF", "Africa"));
        continents.put("GM", new Continent("AF", "Africa"));
        continents.put("GL", new Continent("NA", "North America"));
        continents.put("GI", new Continent("EU", "Europe"));
        continents.put("GH", new Continent("AF", "Africa"));
        continents.put("OM", new Continent("AS", "Asia"));
        continents.put("TN", new Continent("AF", "Africa"));
        continents.put("JO", new Continent("AS", "Asia"));
        continents.put("HR", new Continent("EU", "Europe"));
        continents.put("HT", new Continent("NA", "North America"));
        continents.put("HU", new Continent("EU", "Europe"));
        continents.put("HK", new Continent("AS", "Asia"));
        continents.put("HN", new Continent("NA", "North America"));
        continents.put("HM", new Continent("AN", "Antarctica"));
        continents.put("VE", new Continent("SA", "South America"));
        continents.put("PR", new Continent("NA", "North America"));
        continents.put("PS", new Continent("AS", "Asia"));
        continents.put("PW", new Continent("OC", "Oceania"));
        continents.put("PT", new Continent("EU", "Europe"));
        continents.put("SJ", new Continent("EU", "Europe"));
        continents.put("PY", new Continent("SA", "South America"));
        continents.put("IQ", new Continent("AS", "Asia"));
        continents.put("PA", new Continent("NA", "North America"));
        continents.put("PF", new Continent("OC", "Oceania"));
        continents.put("PG", new Continent("OC", "Oceania"));
        continents.put("PE", new Continent("SA", "South America"));
        continents.put("PK", new Continent("AS", "Asia"));
        continents.put("PH", new Continent("AS", "Asia"));
        continents.put("PN", new Continent("OC", "Oceania"));
        continents.put("PL", new Continent("EU", "Europe"));
        continents.put("PM", new Continent("NA", "North America"));
        continents.put("ZM", new Continent("AF", "Africa"));
        continents.put("EH", new Continent("AF", "Africa"));
        continents.put("EE", new Continent("EU", "Europe"));
        continents.put("EG", new Continent("AF", "Africa"));
        continents.put("ZA", new Continent("AF", "Africa"));
        continents.put("EC", new Continent("SA", "South America"));
        continents.put("IT", new Continent("EU", "Europe"));
        continents.put("VN", new Continent("AS", "Asia"));
        continents.put("SB", new Continent("OC", "Oceania"));
        continents.put("ET", new Continent("AF", "Africa"));
        continents.put("SO", new Continent("AF", "Africa"));
        continents.put("ZW", new Continent("AF", "Africa"));
        continents.put("SA", new Continent("AS", "Asia"));
        continents.put("ES", new Continent("EU", "Europe"));
        continents.put("ER", new Continent("AF", "Africa"));
        continents.put("ME", new Continent("EU", "Europe"));
        continents.put("MD", new Continent("EU", "Europe"));
        continents.put("MG", new Continent("AF", "Africa"));
        continents.put("MF", new Continent("NA", "North America"));
        continents.put("MA", new Continent("AF", "Africa"));
        continents.put("MC", new Continent("EU", "Europe"));
        continents.put("UZ", new Continent("AS", "Asia"));
        continents.put("MM", new Continent("AS", "Asia"));
        continents.put("ML", new Continent("AF", "Africa"));
        continents.put("MO", new Continent("AS", "Asia"));
        continents.put("MN", new Continent("AS", "Asia"));
        continents.put("MH", new Continent("OC", "Oceania"));
        continents.put("MK", new Continent("EU", "Europe"));
        continents.put("MU", new Continent("AF", "Africa"));
        continents.put("MT", new Continent("EU", "Europe"));
        continents.put("MW", new Continent("AF", "Africa"));
        continents.put("MV", new Continent("AS", "Asia"));
        continents.put("MQ", new Continent("NA", "North America"));
        continents.put("MP", new Continent("OC", "Oceania"));
        continents.put("MS", new Continent("NA", "North America"));
        continents.put("MR", new Continent("AF", "Africa"));
        continents.put("IM", new Continent("EU", "Europe"));
        continents.put("UG", new Continent("AF", "Africa"));
        continents.put("TZ", new Continent("AF", "Africa"));
        continents.put("MY", new Continent("AS", "Asia"));
        continents.put("MX", new Continent("NA", "North America"));
        continents.put("IL", new Continent("AS", "Asia"));
        continents.put("FR", new Continent("EU", "Europe"));
        continents.put("IO", new Continent("AS", "Asia"));
        continents.put("SH", new Continent("AF", "Africa"));
        continents.put("FI", new Continent("EU", "Europe"));
        continents.put("FJ", new Continent("OC", "Oceania"));
        continents.put("FK", new Continent("SA", "South America"));
        continents.put("FM", new Continent("OC", "Oceania"));
        continents.put("FO", new Continent("EU", "Europe"));
        continents.put("NI", new Continent("NA", "North America"));
        continents.put("NL", new Continent("EU", "Europe"));
        continents.put("NO", new Continent("EU", "Europe"));
        continents.put("NA", new Continent("AF", "Africa"));
        continents.put("VU", new Continent("OC", "Oceania"));
        continents.put("NC", new Continent("OC", "Oceania"));
        continents.put("NE", new Continent("AF", "Africa"));
        continents.put("NF", new Continent("OC", "Oceania"));
        continents.put("NG", new Continent("AF", "Africa"));
        continents.put("NZ", new Continent("OC", "Oceania"));
        continents.put("NP", new Continent("AS", "Asia"));
        continents.put("NR", new Continent("OC", "Oceania"));
        continents.put("NU", new Continent("OC", "Oceania"));
        continents.put("CK", new Continent("OC", "Oceania"));
        continents.put("XK", new Continent("EU", "Europe"));
        continents.put("CI", new Continent("AF", "Africa"));
        continents.put("CH", new Continent("EU", "Europe"));
        continents.put("CO", new Continent("SA", "South America"));
        continents.put("CN", new Continent("AS", "Asia"));
        continents.put("CM", new Continent("AF", "Africa"));
        continents.put("CL", new Continent("SA", "South America"));
        continents.put("CC", new Continent("AS", "Asia"));
        continents.put("CA", new Continent("NA", "North America"));
        continents.put("CG", new Continent("AF", "Africa"));
        continents.put("CF", new Continent("AF", "Africa"));
        continents.put("CD", new Continent("AF", "Africa"));
        continents.put("CZ", new Continent("EU", "Europe"));
        continents.put("CY", new Continent("EU", "Europe"));
        continents.put("CX", new Continent("AS", "Asia"));
        continents.put("CR", new Continent("NA", "North America"));
        continents.put("CW", new Continent("NA", "North America"));
        continents.put("CV", new Continent("AF", "Africa"));
        continents.put("CU", new Continent("NA", "North America"));
        continents.put("SZ", new Continent("AF", "Africa"));
        continents.put("SY", new Continent("AS", "Asia"));
        continents.put("SX", new Continent("NA", "North America"));
        continents.put("KG", new Continent("AS", "Asia"));
        continents.put("KE", new Continent("AF", "Africa"));
        continents.put("SS", new Continent("AF", "Africa"));
        continents.put("SR", new Continent("SA", "South America"));
        continents.put("KI", new Continent("OC", "Oceania"));
        continents.put("KH", new Continent("AS", "Asia"));
        continents.put("KN", new Continent("NA", "North America"));
        continents.put("KM", new Continent("AF", "Africa"));
        continents.put("ST", new Continent("AF", "Africa"));
        continents.put("SK", new Continent("EU", "Europe"));
        continents.put("KR", new Continent("AS", "Asia"));
        continents.put("SI", new Continent("EU", "Europe"));
        continents.put("KP", new Continent("AS", "Asia"));
        continents.put("KW", new Continent("AS", "Asia"));
        continents.put("SN", new Continent("AF", "Africa"));
        continents.put("SM", new Continent("EU", "Europe"));
        continents.put("SL", new Continent("AF", "Africa"));
        continents.put("SC", new Continent("AF", "Africa"));
        continents.put("KZ", new Continent("AS", "Asia"));
        continents.put("KY", new Continent("NA", "North America"));
        continents.put("SG", new Continent("AS", "Asia"));
        continents.put("SE", new Continent("EU", "Europe"));
        continents.put("SD", new Continent("AF", "Africa"));
        continents.put("DO", new Continent("NA", "North America"));
        continents.put("DM", new Continent("NA", "North America"));
        continents.put("DJ", new Continent("AF", "Africa"));
        continents.put("DK", new Continent("EU", "Europe"));
        continents.put("VG", new Continent("NA", "North America"));
        continents.put("DE", new Continent("EU", "Europe"));
        continents.put("YE", new Continent("AS", "Asia"));
        continents.put("DZ", new Continent("AF", "Africa"));
        continents.put("US", new Continent("NA", "North America"));
        continents.put("UY", new Continent("SA", "South America"));
        continents.put("YT", new Continent("AF", "Africa"));
        continents.put("UM", new Continent("OC", "Oceania"));
        continents.put("LB", new Continent("AS", "Asia"));
        continents.put("LC", new Continent("NA", "North America"));
        continents.put("LA", new Continent("AS", "Asia"));
        continents.put("TV", new Continent("OC", "Oceania"));
        continents.put("TW", new Continent("AS", "Asia"));
        continents.put("TT", new Continent("NA", "North America"));
        continents.put("TR", new Continent("AS", "Asia"));
        continents.put("LK", new Continent("AS", "Asia"));
        continents.put("LI", new Continent("EU", "Europe"));
        continents.put("LV", new Continent("EU", "Europe"));
        continents.put("TO", new Continent("OC", "Oceania"));
        continents.put("LT", new Continent("EU", "Europe"));
        continents.put("LU", new Continent("EU", "Europe"));
        continents.put("LR", new Continent("AF", "Africa"));
        continents.put("LS", new Continent("AF", "Africa"));
        continents.put("TH", new Continent("AS", "Asia"));
        continents.put("TF", new Continent("AN", "Antarctica"));
        continents.put("TG", new Continent("AF", "Africa"));
        continents.put("TD", new Continent("AF", "Africa"));
        continents.put("TC", new Continent("NA", "North America"));
        continents.put("LY", new Continent("AF", "Africa"));
        continents.put("VA", new Continent("EU", "Europe"));
        continents.put("VC", new Continent("NA", "North America"));
        continents.put("AE", new Continent("AS", "Asia"));
        continents.put("AD", new Continent("EU", "Europe"));
        continents.put("AG", new Continent("NA", "North America"));
        continents.put("AF", new Continent("AS", "Asia"));
        continents.put("AI", new Continent("NA", "North America"));
        continents.put("VI", new Continent("NA", "North America"));
        continents.put("IS", new Continent("EU", "Europe"));
        continents.put("IR", new Continent("AS", "Asia"));
        continents.put("AM", new Continent("AS", "Asia"));
        continents.put("AL", new Continent("EU", "Europe"));
        continents.put("AO", new Continent("AF", "Africa"));
        continents.put("AQ", new Continent("AN", "Antarctica"));
        continents.put("AS", new Continent("OC", "Oceania"));
        continents.put("AR", new Continent("SA", "South America"));
        continents.put("AU", new Continent("OC", "Oceania"));
        continents.put("AT", new Continent("EU", "Europe"));
        continents.put("AW", new Continent("NA", "North America"));
        continents.put("IN", new Continent("AS", "Asia"));
        continents.put("AX", new Continent("EU", "Europe"));
        continents.put("AZ", new Continent("AS", "Asia"));
        continents.put("IE", new Continent("EU", "Europe"));
        continents.put("ID", new Continent("AS", "Asia"));
        continents.put("UA", new Continent("EU", "Europe"));
        continents.put("QA", new Continent("AS", "Asia"));
        continents.put("MZ", new Continent("AF", "Africa"));
    }
}
